apiHost: albh2.aitmed.io
apiPort: '443' 
webApiHost: apiHost 
appApiHost: apiHost 
connectiontimeout: '5' 
loadingLevel: 1 
debug: console_log_api
cadlBaseUrl: https://public.aitmed.com/cadl/testpage2_0.9/
cadlMain: cadlEndpoint.yml
timestamp: 09132021PDT
