apiHost: albh2.aitmed.io
apiPort: '443'
webApiHost: apiHost
appApiHost: apiHost
connectiontimeout: '5'
loadingLevel: 1
debug: console_log_api
viewWidthHeightRatio:
    min: 0.56
    max: 0.7
web:
  cadlVersion :
    stable: 0.88d
    test : 0.88d
ios:
  cadlVersion:
    stable: 0.88d
    test : 0.88d
android:
  cadlVersion:
    stable : 0.88d
    test : 0.88d
cadlBaseUrl: https://public.aitmed.com/cadl/meet2_${cadlVersion}/
cadlMain: cadlEndpoint.yml
timestamp: 03112021
myBaseUrl: https://public.aitmed.com/cadl/meet2_0.88d/
keywords:
  - telemedicine
  - Telehealth
  - Blockchain Telemedicine
  - Fast, Private, Secure
  - Blockchain Telehealth Platform
  - HIPAA Compliance
  - Pandemic
  - Covid19
  - Wellness and illness
  - Telemedicine clinic
  - Telemedicine Pediatric
  - Telemedicine Urgent Care
  - Telemedicine dermatology
  - Telemedicine Senior House
  - Telemedicine Hospital
  - Telemedicine RADIOLOGY
  - Telemedicine Neurology 
  - Telehealth Lab 
  - Telehealth Pandemic
  - Telehealth Covid19
  - Telehealth clinic
  - Telehealth Pediatric
  - Telehealth Urgent Care
  - Telehealth dermatology
  - Telehealth Senior House
  - Telehealth Hospital
  - Telehealth RADIOLOGY
  - Telehealth Neurology 
  - Telehealth Lab 
  - Doctor Virtual Platform
  - Telemedicine Imaging 
  - Online Medical Practice 
  - Online schedule 
  - E-prescription 
  - Virtual Meeting Room 
  - Virtual platform 
  - Secure Platform 
  - Virtual Visit 
  - Private Visit 
  - doctor 
  - patient 
  - chronic illness 
  - Medical clinic 
  - medical platform 
  - Medical knowledge 
  - telecommunication 
  - virtual 
  - Vital Sign
