apiHost: albh2.aitmed.io
apiPort: '443'
webApiHost: apiHost
appApiHost: apiHost
connectiontimeout: '5'
loadingLevel: 1
debug: console_log_api
web:
  cadlVersion :
    stable: 2.16c
    test : 2.16c
ios:
  cadlVersion:
    stable: 2.16c
    test : 2.16c
android:
  cadlVersion:
    stable : 2.16c
    test : 2.16c
cadlBaseUrl: https://public.aitmed.com/cadl/patient${cadlVersion}/
cadlMain: cadlEndpoint.yml
timestamp: 09022020
