apiHost: albh2.aitmed.io
apiPort: '443'
webApiHost: apiHost
appApiHost: apiHost
connectiontimeout: '5'
loadingLevel: 1
debug: console_log_api
web:
  cadlVersion :
    stable: 3.34
    test : 3.34
ios:
  cadlVersion:
    stable: 3.34
    test : 3.34
android:
  cadlVersion:
    stable : 3.34
    test : 3.34
cadlBaseUrl: https://public.aitmed.com/cadl/patient${cadlVersion}/
cadlMain: cadlEndpoint.yml
timestamp: 09022020
