apiHost: albh2.aitmed.io
apiPort: '443'
webApiHost: apiHost
appApiHost: apiHost
connectiontimeout: '5'
loadingLevel: 1
debug: console_log_api
web:
  cadlVersion :
    stable: 02t
    test : 02t
ios:
  cadlVersion:
    stable: 02t
    test : 02t
android:
  cadlVersion:
    stable : 02t
    test : 02t
cadlBaseUrl: https://public.aitmed.com/cadl/patient_${cadlVersion}/
cadlMain: cadlEndpoint.yml
timestamp: 04292021
